In [1]:
# Step 2.0 – Import libraries
import pandas as pd

# Step 2.1 – Load datasets with correct encoding
movies = pd.read_csv('movies.dat', sep='::', engine='python', 
                     names=['MovieID', 'Title', 'Genres'], encoding='ISO-8859-1')

ratings = pd.read_csv('ratings.dat', sep='::', engine='python', 
                      names=['UserID', 'MovieID', 'Rating', 'Timestamp'], encoding='ISO-8859-1')

users = pd.read_csv('users.dat', sep='::', engine='python', 
                    names=['UserID', 'Gender', 'Age', 'Occupation', 'Zip-code'], encoding='ISO-8859-1')

In [2]:
# Step 2.2 – Basic info about data
print("Movies shape:", movies.shape)
print("Ratings shape:", ratings.shape)
print("Users shape:", users.shape)

# Check for missing values
print("\nMissing values in movies:\n", movies.isnull().sum())
print("\nMissing values in ratings:\n", ratings.isnull().sum())
print("\nMissing values in users:\n", users.isnull().sum())

Movies shape: (3883, 3)
Ratings shape: (1000209, 4)
Users shape: (6040, 5)

Missing values in movies:
 MovieID    0
Title      0
Genres     0
dtype: int64

Missing values in ratings:
 UserID       0
MovieID      0
Rating       0
Timestamp    0
dtype: int64

Missing values in users:
 UserID        0
Gender        0
Age           0
Occupation    0
Zip-code      0
dtype: int64

In [3]:
# Step 2.3 – Quick look at genres and rating distribution
print("\nUnique genres:\n", movies['Genres'].unique())

# Rating distribution
print("\nRatings summary:\n", ratings['Rating'].describe())
ratings['Rating'].value_counts().sort_index()

Unique genres:
 ["Animation|Children's|Comedy" "Adventure|Children's|Fantasy"
 'Comedy|Romance' 'Comedy|Drama' 'Comedy' 'Action|Crime|Thriller'
 "Adventure|Children's" 'Action' 'Action|Adventure|Thriller'
 'Comedy|Drama|Romance' 'Comedy|Horror' "Animation|Children's" 'Drama'
 'Action|Adventure|Romance' 'Drama|Thriller' 'Drama|Romance' 'Thriller'
 'Action|Comedy|Drama' 'Crime|Drama|Thriller' 'Drama|Sci-Fi' 'Romance'
 'Adventure|Sci-Fi' 'Adventure|Romance' "Children's|Comedy|Drama"
 'Documentary' 'Drama|War' 'Action|Crime|Drama' 'Action|Adventure'
 'Crime|Thriller' "Animation|Children's|Musical|Romance"
 'Action|Drama|Thriller' "Children's|Comedy" 'Drama|Mystery'
 'Sci-Fi|Thriller' 'Action|Comedy|Crime|Horror|Thriller' 'Drama|Musical'
 'Crime|Drama|Romance' 'Adventure|Drama' 'Action|Thriller'
 "Adventure|Children's|Comedy|Musical" 'Action|Drama|War'
 'Action|Adventure|Crime' 'Crime' 'Drama|Mystery|Romance' 'Action|Drama'
 'Drama|Romance|War' 'Horror' 'Action|Adventure|Comedy|Crime' 'Comedy|War'
 'Action|Adventure|Mystery|Sci-Fi' 'Drama|Thriller|War'
 'Action|Romance|Thriller' 'Crime|Film-Noir|Mystery|Thriller'
 'Action|Adventure|Drama|Romance' "Adventure|Children's|Drama"
 'Action|Sci-Fi|Thriller' 'Action|Adventure|Sci-Fi' "Action|Children's"
 'Horror|Sci-Fi' 'Action|Crime|Sci-Fi' 'Western'
 "Animation|Children's|Comedy|Romance" "Children's|Drama" 'Crime|Drama'
 'Drama|Fantasy|Romance|Thriller' 'Drama|Horror' 'Comedy|Sci-Fi'
 'Mystery|Thriller' "Adventure|Children's|Comedy|Fantasy|Romance"
 'Action|Adventure|Fantasy|Sci-Fi' 'Drama|Romance|War|Western'
 'Action|Crime' 'Crime|Drama|Romance|Thriller' 'Action|Adventure|Western'
 'Horror|Thriller' "Children's|Comedy|Fantasy" 'Film-Noir|Thriller'
 'Action|Comedy|Musical|Sci-Fi' "Children's" 'Drama|Mystery|Thriller'
 'Comedy|Romance|War' 'Action|Comedy' "Adventure|Children's|Romance"
 "Animation|Children's|Musical" 'Comedy|Crime|Fantasy'
 'Action|Comedy|Western' 'Action|Sci-Fi' 'Action|Adventure|Comedy|Romance'
 'Comedy|Crime|Drama' 'Comedy|Thriller' 'Horror|Sci-Fi|Thriller'
 'Mystery|Romance|Thriller' 'Comedy|Western' 'Drama|Western'
 'Action|Adventure|Crime|Thriller' 'Action|Comedy|War' 'Comedy|Mystery'
 'Comedy|Mystery|Romance' 'Comedy|Drama|War' 'Action|Drama|Mystery'
 'Comedy|Crime|Horror' 'Film-Noir|Sci-Fi' 'Comedy|Romance|Thriller'
 "Action|Adventure|Children's|Sci-Fi" "Children's|Comedy|Musical"
 'Action|Adventure|Comedy' 'Action|Crime|Romance'
 "Action|Adventure|Animation|Children's|Fantasy"
 "Animation|Children's|Comedy|Musical" 'Adventure|Drama|Western'
 'Action|Adventure|Crime|Drama' 'Action|Adventure|Animation|Horror|Sci-Fi'
 'Action|Horror|Sci-Fi' 'War' 'Action|Adventure|Mystery' 'Mystery'
 'Action|Adventure|Fantasy'
 "Adventure|Animation|Children's|Comedy|Fantasy" 'Sci-Fi'
 'Documentary|Drama' 'Action|Adventure|Comedy|War'
 'Crime|Film-Noir|Thriller' 'Animation'
 'Action|Adventure|Romance|Thriller' 'Animation|Sci-Fi'
 'Animation|Comedy|Thriller' 'Film-Noir' 'Sci-Fi|War' 'Adventure'
 'Comedy|Crime' 'Action|Sci-Fi|War' 'Comedy|Fantasy|Romance|Sci-Fi'
 'Fantasy' 'Action|Mystery|Thriller' 'Comedy|Musical'
 'Action|Adventure|Sci-Fi|Thriller' "Children's|Drama|Fantasy"
 'Adventure|War' 'Musical|Romance' 'Comedy|Musical|Romance'
 'Comedy|Mystery|Romance|Thriller' 'Film-Noir|Mystery' 'Musical'
 "Adventure|Children's|Drama|Musical" 'Drama|Mystery|Sci-Fi|Thriller'
 'Romance|Thriller' 'Film-Noir|Romance|Thriller' 'Crime|Film-Noir|Mystery'
 'Adventure|Comedy' 'Action|Adventure|Romance|War' 'Romance|War'
 'Action|Drama|Western' "Children's|Comedy|Western"
 "Adventure|Children's|Comedy" "Children's|Comedy|Mystery"
 "Adventure|Children's|Fantasy|Sci-Fi"
 "Adventure|Animation|Children's|Musical" "Adventure|Children's|Musical"
 'Crime|Film-Noir' "Adventure|Children's|Comedy|Fantasy"
 "Children's|Drama|Fantasy|Sci-Fi" 'Action|Romance' 'Adventure|Western'
 'Comedy|Fantasy' 'Animation|Comedy' 'Crime|Drama|Film-Noir'
 'Action|Adventure|Drama|Sci-Fi|War' 'Action|Sci-Fi|Thriller|War'
 'Action|Western' "Action|Animation|Children's|Sci-Fi|Thriller|War"
 'Action|Adventure|Romance|Sci-Fi|War' 'Action|Horror|Sci-Fi|Thriller'
 'Action|Adventure|Comedy|Horror|Sci-Fi' 'Action|Comedy|Musical'
 'Mystery|Sci-Fi' 'Film-Noir|Mystery|Thriller' 'Adventure|Comedy|Drama'
 'Action|Adventure|Comedy|Horror' 'Action|Drama|Mystery|Romance|Thriller'
 'Comedy|Mystery|Thriller' 'Adventure|Animation|Sci-Fi|Thriller'
 'Action|Drama|Romance' 'Action|Adventure|Drama' 'Comedy|Drama|Musical'
 'Documentary|War' 'Drama|Musical|War' 'Action|Horror' 'Horror|Romance'
 'Action|Comedy|Sci-Fi|War' 'Crime|Drama|Sci-Fi' 'Action|Romance|War'
 'Action|Comedy|Crime|Drama' 'Action|Drama|Thriller|War'
 "Action|Adventure|Children's" "Action|Adventure|Children's|Fantasy"
 "Adventure|Animation|Children's|Comedy|Musical" 'Crime|Drama|Mystery'
 'Action|Adventure|Comedy|Sci-Fi' "Children's|Fantasy"
 'Action|Mystery|Sci-Fi|Thriller' 'Action|Mystery|Romance|Thriller'
 'Adventure|Thriller' 'Action|Thriller|War' 'Action|Crime|Mystery'
 'Horror|Mystery|Thriller' 'Crime|Horror|Mystery|Thriller'
 'Comedy|Drama|Thriller' 'Drama|Sci-Fi|Thriller' 'Drama|Romance|Thriller'
 'Action|Adventure|Sci-Fi|War' 'Comedy|Crime|Drama|Mystery'
 'Comedy|Crime|Mystery|Thriller' 'Film-Noir|Sci-Fi|Thriller'
 'Adventure|Sci-Fi|Thriller' 'Crime|Drama|Mystery|Thriller'
 'Comedy|Documentary' 'Documentary|Musical' 'Action|Drama|Sci-Fi|Thriller'
 "Adventure|Animation|Children's|Fantasy" 'Adventure|Comedy|Romance'
 'Mystery|Sci-Fi|Thriller' 'Action|Comedy|Crime'
 "Animation|Children's|Fantasy|War" 'Action|Crime|Drama|Thriller'
 'Comedy|Sci-Fi|Western' "Children's|Fantasy|Musical" 'Fantasy|Sci-Fi'
 "Children's|Comedy|Sci-Fi" "Action|Adventure|Children's|Comedy"
 "Adventure|Children's|Drama|Romance" "Adventure|Children's|Sci-Fi"
 "Adventure|Children's|Comedy|Fantasy|Sci-Fi"
 "Animation|Children's|Comedy|Musical|Romance" "Children's|Musical"
 'Drama|Fantasy' "Animation|Children's|Fantasy|Musical"
 'Adventure|Comedy|Musical' "Children's|Sci-Fi" "Children's|Horror"
 'Comedy|Fantasy|Romance' 'Comedy|Crime|Thriller'
 "Adventure|Animation|Children's|Sci-Fi" 'Action|Crime|Mystery|Thriller'
 'Adventure|Musical' "Animation|Children's|Drama|Fantasy"
 "Children's|Fantasy|Sci-Fi" 'Adventure|Fantasy|Romance' 'Crime|Horror'
 'Action|Adventure|Horror' 'Adventure|Fantasy|Sci-Fi'
 'Drama|Film-Noir|Thriller' 'Action|Comedy|Fantasy' 'Sci-Fi|Thriller|War'
 'Action|Adventure|Sci-Fi|Thriller|War' 'Action|Adventure|Drama|Thriller'
 'Crime|Horror|Thriller' 'Animation|Musical' 'Action|War'
 'Action|Comedy|Romance|Thriller' 'Comedy|Horror|Thriller'
 'Drama|Horror|Thriller' 'Action|Sci-Fi|Thriller|Western'
 'Drama|Romance|Sci-Fi' 'Action|Adventure|Horror|Thriller'
 'Comedy|Film-Noir|Thriller' 'Comedy|Horror|Musical|Sci-Fi'
 'Comedy|Romance|Sci-Fi' 'Action|Comedy|Sci-Fi|Thriller'
 'Action|Sci-Fi|Western' 'Comedy|Horror|Musical' 'Crime|Mystery'
 'Animation|Mystery' 'Action|Horror|Thriller'
 'Action|Drama|Fantasy|Romance' 'Horror|Mystery'
 "Adventure|Animation|Children's" 'Musical|Romance|War'
 'Adventure|Drama|Romance' 'Adventure|Animation|Film-Noir'
 'Action|Adventure|Animation' 'Comedy|Drama|Western'
 'Adventure|Comedy|Sci-Fi' 'Drama|Romance|Western' 'Comedy|Drama|Sci-Fi'
 'Action|Drama|Romance|Thriller' 'Adventure|Romance|Sci-Fi'
 'Film-Noir|Horror' 'Crime|Drama|Film-Noir|Thriller'
 'Action|Adventure|War' 'Romance|Western' "Action|Children's|Fantasy"
 'Adventure|Drama|Thriller' 'Adventure|Fantasy' 'Musical|War'
 'Adventure|Musical|Romance' 'Action|Romance|Sci-Fi' 'Drama|Film-Noir'
 'Comedy|Horror|Sci-Fi' 'Adventure|Drama|Romance|Sci-Fi'
 'Adventure|Animation|Sci-Fi' 'Adventure|Crime|Sci-Fi|Thriller']

Ratings summary:
 count    1.000209e+06
mean     3.581564e+00
std      1.117102e+00
min      1.000000e+00
25%      3.000000e+00
50%      4.000000e+00
75%      4.000000e+00
max      5.000000e+00
Name: Rating, dtype: float64

Rating
1     56174
2    107557
3    261197
4    348971
5    226310
Name: count, dtype: int64

In [4]:
# Step 2.4 – Merge ratings with users
ratings_users = pd.merge(ratings, users, on='UserID')

# Step 2.5 – Merge the result with movies
full_data = pd.merge(ratings_users, movies, on='MovieID')

# Step 2.6 – Final dataset overview
print("Full merged dataset shape:", full_data.shape)
full_data.head()

Full merged dataset shape: (1000209, 10)

,UserID,MovieID,Rating,Timestamp,Gender,Age,Occupation,Zip-code,Title,Genres
0,1,1193,5,978300760,F,1,10,48067,One Flew Over the Cuckoo's Nest (1975),Drama
1,1,661,3,978302109,F,1,10,48067,James and the Giant Peach (1996),Animation|Children's|Musical
2,1,914,3,978301968,F,1,10,48067,My Fair Lady (1964),Musical|Romance
3,1,3408,4,978300275,F,1,10,48067,Erin Brockovich (2000),Drama
4,1,2355,5,978824291,F,1,10,48067,"Bug's Life, A (1998)",Animation|Children's|Comedy

In [5]:
# Create a pivot table (UserID × Movie Title) with ratings
user_movie_matrix = full_data.pivot_table(index='UserID', columns='Title', values='Rating')

# Show sample
user_movie_matrix.head()

Title,"$1,000,000 Duck (1971)",'Night Mother (1986),'Til There Was You (1997),"'burbs, The (1989)",...And Justice for All (1979),1-900 (1994),10 Things I Hate About You (1999),101 Dalmatians (1961),101 Dalmatians (1996),12 Angry Men (1957),...,"Young Poisoner's Handbook, The (1995)",Young Sherlock Holmes (1985),Young and Innocent (1937),Your Friends and Neighbors (1998),Zachariah (1971),"Zed & Two Noughts, A (1985)",Zero Effect (1998),Zero Kelvin (Kjærlighetens kjøtere) (1995),Zeus and Roxanne (1997),eXistenZ (1999)
UserID,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Split genres into separate columns using One Hot Encoding
movies_expanded = movies.copy()
movies_expanded['Genres'] = movies_expanded['Genres'].str.split('|')

# One-hot encode genres
genres_encoded = movies_expanded['Genres'].explode().str.get_dummies().groupby(movies_expanded['MovieID']).max()

# Merge genre info back with movies
movie_profiles = pd.merge(movies[['MovieID', 'Title']], genres_encoded, left_on='MovieID', right_index=True)

# Show movie profiles
movie_profiles.head()

,MovieID,Title,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0
4,5,Father of the Bride Part II (1995),0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [7]:
from sklearn.metrics.pairwise import cosine_similarity

# Drop non-numeric columns for similarity computation
genre_features = movie_profiles.drop(['MovieID', 'Title'], axis=1)

# Compute cosine similarity between all movies
cosine_sim = cosine_similarity(genre_features)

# Store results in a DataFrame for easier lookup
content_sim_df = pd.DataFrame(cosine_sim, index=movie_profiles['Title'], columns=movie_profiles['Title'])

In [8]:
def get_content_recommendations(movie_title, top_n=10):
    if movie_title not in content_sim_df.index:
        return f"❌ Movie '{movie_title}' not found in database."

    # Get similarity scores and sort
    similar_scores = content_sim_df[movie_title].sort_values(ascending=False)
    
    # Exclude the movie itself and return top N
    recommended_titles = similar_scores.iloc[1:top_n+1].index.tolist()
    return recommended_titles

In [9]:
get_content_recommendations('Toy Story (1995)', top_n=5)

['Adventures of Rocky and Bullwinkle, The (2000)',
 'Aladdin and the King of Thieves (1996)',
 'Chicken Run (2000)',
 'Saludos Amigos (1943)',
 "Bug's Life, A (1998)"]

In [10]:
# Fill NaN values with 0 to make matrix numeric
user_movie_matrix_filled = user_movie_matrix.fillna(0)

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

# Transpose to get Movie × User matrix
movie_user_matrix = user_movie_matrix_filled.T

# Compute cosine similarity between movies
collab_cosine_sim = cosine_similarity(movie_user_matrix)

# Create a DataFrame for easier lookup
collab_sim_df = pd.DataFrame(collab_cosine_sim, index=movie_user_matrix.index, columns=movie_user_matrix.index)

In [12]:
def get_collab_recommendations(movie_title, top_n=10):
    if movie_title not in collab_sim_df.index:
        return f"❌ Movie '{movie_title}' not found in user ratings."

    # Get similarity scores and sort
    similar_scores = collab_sim_df[movie_title].sort_values(ascending=False)

    # Exclude the movie itself
    recommended_titles = similar_scores.iloc[1:top_n+1].index.tolist()
    return recommended_titles

In [13]:
get_collab_recommendations('Toy Story (1995)', top_n=5)

['Toy Story 2 (1999)',
 'Groundhog Day (1993)',
 'Aladdin (1992)',
 "Bug's Life, A (1998)",
 'Back to the Future (1985)']

In [14]:
def hybrid_recommend(movie_title, top_n=10, content_weight=0.5, collab_weight=0.5):
    # Check existence in both models
    if movie_title not in content_sim_df.index or movie_title not in collab_sim_df.index:
        return f"❌ Movie '{movie_title}' not found in both models."

    # Get similarity scores from both models
    content_scores = content_sim_df[movie_title]
    collab_scores = collab_sim_df[movie_title]
    
    # Normalize scores between 0 and 1
    content_scores_norm = (content_scores - content_scores.min()) / (content_scores.max() - content_scores.min())
    collab_scores_norm = (collab_scores - collab_scores.min()) / (collab_scores.max() - collab_scores.min())
    
    # Combine scores using weights
    hybrid_scores = (content_weight * content_scores_norm) + (collab_weight * collab_scores_norm)
    
    # Sort and get top recommendations, excluding the input movie
    hybrid_scores_sorted = hybrid_scores.sort_values(ascending=False).drop(movie_title)
    
    return hybrid_scores_sorted.head(top_n).index.tolist()

In [15]:
# Get hybrid recommendations
hybrid_recommend('Toy Story (1995)', top_n=5)

['Toy Story 2 (1999)',
 "Bug's Life, A (1998)",
 'Aladdin (1992)',
 'Chicken Run (2000)',
 'American Tail, An (1986)']